spring:
  profiles:
	active:
	- dev
---
spring:
  profiles: dev
  application:
    name: AIGOU_PLAT
  eureka:
    client:
      serviceUrl:
        defaultZone: http://127.0.0.1:1001/eureka
  instance:
    prefer-ip-address: true
server:
  port: 5001
    
---
spring:
  profiles: test
  application:
    name: AIGOU_PLAT_TEST
eureka:
  client:
    serviceUrl:
      defaultZone: http://127.0.0.1:1001/eureka
instance:
  prefer-ip-address: true
server:
  port: 5002